version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/app
      - public:/app/public
      - tmp:/app/tmp
    depends_on:
      - app_db
    stdin_open: true
    tty: true
    environment:
      DB_ROOT_USERNAME: root
      DB_USERNAME: development
      DB_PASSWORD: password
      TZ: Asia/Tokyo
      DB_HOST: app_db

  app_db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=development
      - MYSQL_USER=development
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=passwordpassword
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/app_db/data/:/var/lib/mysql
      - ./docker/app_db/conf/my.cnf:/etc/my.cnf.d/my.cnf

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - public:/app/public
      - tmp:/app/tmp
      - http-log:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - web

  fluentd:
    build:
      context: .
      dockerfile: ./docker/fluentd/Dockerfile
    ports:
      - 24224:24224
    volumes:
      - ./docker/fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - http-log:/var/log/nginx
    depends_on:
      - log_db

  log_db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=log
      - MYSQL_USER=log
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=passwordpassword
      - TZ=Asia/Tokyo
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/log_db/data/:/var/lib/mysql
      - ./docker/log_db/conf/my.cnf:/etc/my.cnf.d/my.cnf
      - ./docker/fluentd/initdb.d:/docker-entrypoint-initdb.d

  # metabase:
  #   image: metabase/metabase
  #   volumes:
  #     - "./docker/metabase/data:/metabase-data"
  #   environment:
  #     MB_DB_FILE: /metabase-data/metabase.db
  #     MB_DB_TYPE: mysql
  #     MB_DB_DBNAME: log
  #     MB_DB_PORT: 3306
  #     MB_DB_USER: log
  #     MB_DB_PASS: password
  #     MB_DB_HOST: log_db
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - log_db

volumes:
  public:
  tmp:
  http-log: